# Generated by Django 2.2.5 on 2020-02-05 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('accession', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cik', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=10000)),
                ('period_1', models.FloatField()),
                ('period_1_name', models.CharField(max_length=100)),
                ('period_2', models.FloatField()),
                ('period_2_name', models.CharField(max_length=100)),
                ('period_3', models.FloatField()),
                ('period_3_name', models.CharField(max_length=100)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_search.Filing')),
            ],
        ),
        migrations.AddField(
            model_name='filing',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_search.Ticker'),
        ),
    ]
