# Generated by Django 2.2.5 on 2020-02-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='period_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_3',
            field=models.FloatField(null=True),
        ),
    ]
